# The bind address of the WebSocket used for WebRTC signaling
websocket_address = "0.0.0.0:8085"
# The bind address of the Secure WebSocket used for WebRTC signaling
# Set to an empty string to disable Secure WebSocket
webssocket_address = "0.0.0.0:8086"
# DER Certificate for Secure WebSocket
cert_file = "cert.crt"
# Private Key for Secure WebSocket
private_key_file = "cert.key"
# The bind addresses of the UDP sockets used to receive camera RTP streams
camera_addresses = [
    "0.0.0.0:8100",
    "0.0.0.0:8200",
    "0.0.0.0:8300",
    "0.0.0.0:8400",
    "0.0.0.0:8500",
    "0.0.0.0:8600",
    "0.0.0.0:8700",
    "0.0.0.0:8800",
]
# Log level filter. Select from [Off, Error, Warn, Info, Debug, Trace] (from log::LevelFilter)
log_level = "Debug"
# Rewrite sequence number, timestamp, and synchronization source identifier so clients don't need to reconnect when any stream restarts
rewrite_rtp_header = true
